name: baby_blockchain
description: 0 y.o. and still going

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # blockchain-related
  crypton: ^2.0.5 # elliptic curve keypair + create/verify signature func
  crypto: ^3.0.2 # sha-256
  hex: ^0.2.0 # hex to byte array and vice versa
  
  # backend(firebase)
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  
  # ui
  line_icons: ^2.0.1
  google_fonts: ^2.3.1
  google_nav_bar: ^5.0.6
  flutter_spinkit: ^5.1.0
  glass: ^1.0.1+1

  # service
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/images/
  uses-material-design: true