// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByiSiQfLk5fkfEGvXQV7TYucgZpeGibW0',
    appId: '1:831543032458:web:8ce2dbd8cf92e211c00b73',
    messagingSenderId: '831543032458',
    projectId: 'baby-blockchain',
    authDomain: 'baby-blockchain.firebaseapp.com',
    storageBucket: 'baby-blockchain.appspot.com',
    measurementId: 'G-SDNX1LEPGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjTlsucGL080uducTFuc02oaYsUv0ji3I',
    appId: '1:831543032458:android:99765c560200a8a8c00b73',
    messagingSenderId: '831543032458',
    projectId: 'baby-blockchain',
    storageBucket: 'baby-blockchain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpeQQSuodnCEqeMRbHeX6fCRBJvK4nXus',
    appId: '1:831543032458:ios:91e5e6170b545998c00b73',
    messagingSenderId: '831543032458',
    projectId: 'baby-blockchain',
    storageBucket: 'baby-blockchain.appspot.com',
    iosClientId: '831543032458-9bl0b9fmr7nhd8j8rqasd8mn8mlerogb.apps.googleusercontent.com',
    iosBundleId: 'com.example.babyBlockchain',
  );
}
